[env:esp32h2]
platform = https://github.com/pioarduino/platform-espressif32/releases/latest/download/platform-espressif32.zip
board = esp32-h2-devkitm-1
framework = arduino
monitor_speed = 115200

board_build.filesystem = littlefs
board_build.partitions = default.csv    ; (any stock CSV with a FS partition is fine)
