(part "24AA02E48T-I_OT"
    (packageRef "SOT95P270X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "SCL") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VSS") (portType INOUT))
        (port "3" (symbPinId 3) (portName "SDA") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VCC") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "24AA02E48T-I/OT")
    (property "Mouser_Part_Number" "579-24AA02E48TIOT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology/24AA02E48T-I-OT?qs=h8kCHL4kpM5dzsPTuTrxSQ%3D%3D")
    (property "Arrow_Part_Number" "24AA02E48T-I/OT")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/24aa02e48t-iot/microchip-technology?utm_currency=USD&region=nac")
    (property "Description" "2K 256X8 1.8V Ser.EEPROM,24AA02E48T-I/OT")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/SFDatasheet-11/sf-000234844.pdf")
    (property "symbolName1" "24AA02E48T-I_OT")
)
