(part "MCP3021A5T-E_OT"
    (packageRef "SOT95P280X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "VDD") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VSS") (portType INOUT))
        (port "3" (symbPinId 3) (portName "AIN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SDA") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SCL") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "MCP3021A5T-E/OT")
    (property "Mouser_Part_Number" "579-MCP3021A5T-E/OT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology/MCP3021A5T-E-OT?qs=gySgac5WNsGj4n43R%252BIXjw%3D%3D")
    (property "Arrow_Part_Number" "MCP3021A5T-E/OT")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/mcp3021a5t-eot/microchip-technology?utm_currency=USD&region=nac")
    (property "Description" "Analog to Digital Converters - ADC 10-bit I2C Sgl Chnl")
    (property "Datasheet_Link" "https://lcsc.componentsearchengine.com/Datasheets/2/MCP3021A5T-E_OT.pdf")
    (property "symbolName1" "MCP3021A5T-E_OT")
)
